name: Build Finicky
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: ./scripts/install.sh
      - run: ./scripts/build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: finicky-app
          path: apps/Finicky/build/Build/Products/Release/Finicky.app
